
<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
<link rel="stylesheet" type="text/css" href="jquery-easyui-1.4.5/themes/default/easyui.css">
    <link rel="stylesheet" type="text/css" href="jquery-easyui-1.4.5/themes/icon.css">
    <link rel="stylesheet" type="text/css" href="jquery-easyui-1.4.5/demo.css">
    <script type="text/javascript" src="jquery-easyui-1.4.5/jquery.min.js"></script>
    <script type="text/javascript" src="jquery-easyui-1.4.5/jquery.easyui.min.js"></script>

<style type="text/css">
#upleft { 
   width:700px; 
   height: 600px; 
   background:; float:left; 
}

#upright { 
   width:500px; 
   height:600px; 
   background:green; 
   float:left
}
</style>
<style>
body {background-color: ;}
h1   {color: blue;}
p    {color: black;}
</style>
</head>
<body>
        
    <div id="upleft" style="height:600px;">
    <table style="width: 610px;height: 600px;">
    
    <tr><td>
             
             <h1 style="color:blue;">WE THINK OUTSIDE THE BOX!</h1><br />
</strong></h4>
<p>Online Property Sales was founded early 2014 by the Principal Carissa Spicer after working in real estate sales and real estate marketing businesses for over 15 years.</p>
<p>Carissa realized that there was a need for a smarter real estate service that not only offered effective and affordable advertising but also offers professional real estate services anywhere, anytime!</p>
<p>We are now the only agency of its kind offering all selling options &#8211; Full Professional Services, Agent Assisted Sales and DIY !</p>
<p>Our fully licensed agents operate virtual offices and whilst they are part of our team, at the same time they are running their own business independently with the support of head office. This enables our team to work in areas of their choice without any office distractions so they can focus on your sale. It also means we have less overheads so we don&#8217;t ask you for expensive marketing campaigns to cover our branding costs!</p>
<p><strong>We do all of our marketing campaigns ONLINE.  </strong>Online Property Sales was developed upon realizing that print advertising and other advertising mediums were not measurable, non targeted, ineffective and expensive! Having extensive experience in the industry, we certainly understand the power and importance of the world wide web.</p>
<p>Most of our business is generated by past clients and referrals which is a massive compliment to our service. We work hard and we sell properties fast so start packing!</p>
<p>If you are looking to buy, sell or rent anywhere on the Sunshine Coast , call us for a chat or you can find us online, anywhere, anytime…and we will put you in touch with your nearest agent.</p>
<p><strong>Ph:  07 5313 4008     </strong></p>
<p>Online Property Sales Pvt Ltd</p>
<p>ACN: <b>8096 121 946</b></p>
<p>&nbsp;</p>

                </td></tr>
                <tr><td>
                <img src="images/Home/aboutus1.jpg" alt="Mountain View" style="width:170px;height:150px;">&nbsp;&nbsp;&nbsp;&nbsp;
                <img src="images/Home/self-parking.jpg" alt="Mountain View" style="width:170px;height:150px;">&nbsp;&nbsp;&nbsp;&nbsp;
                <img src="images/Home/aboutus2.jpg" alt="Mountain View" style="width:170px;height:150px;">
                </td></tr>
                </table>

            </div>

           <div id="upright" style="height:600px;">
           <div style="height: 300px"><br><br><br><br><br>
                    <table style="width: 500px">
    
                        <tr><td>______________________________________</td></tr>
                        <tr>
                       
                            <td><b>General Enquiries:</b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;08096 121 946</td>
                        </tr>
                        <tr><td>_______________________________________
                        </td></tr>
                        <tr>
                            <td><b>Customer Services:</b> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;onlinesales@property.com</td>
                        </tr>
                        </table>
                        </div>
                       <div style="height: 400px;width: 400px">
                        <table>
                        
                        <tr>
                        <td style="background-color: orange">
                         <br>
                       <img src="images/Home/world-political-map (1).jpg" alt="Mountain View" style="width:40px;height:20px;">
                        <h4><font color="white">
                       
                        
                        &nbsp;&nbsp;&nbsp;Our aim moving forwards is to remain 
                        &nbsp;&nbsp;&nbsp;We do all of our marketing campaigns ONLINE
                        &nbsp;&nbsp;&nbsp;If you are looking to buy, sell or rent anywhere on the Sunshine Coast , call us for a chat or you can find us online, anywhere, anytime…and we will put you in touch with your nearest agent.
                        &nbsp;&nbsp;&nbsp;and staff so that we can offer our customers 
                        &nbsp;&nbsp;&nbsp;an ever improving experience.
                        <br>
                        &nbsp;
                        <br>
                        &nbsp;
                        </font>
                    </h4>
                        </td>
                        </tr>
                    </table>
                    </div>
                </div>
               
    

    
   

    

  

</body>
</html>
