/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-01-30 08:32:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.Agent;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class viewusers_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/H:/Nagesh_Office_Work/Oline-Property-Sales/OnlinePropertySale/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OnlinePropertySale/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/org.springframework.web.servlet-3.0.1.RELEASE-A.jar", Long.valueOf(1508810930000L));
    _jspx_dependants.put("jar:file:/H:/Nagesh_Office_Work/Oline-Property-Sales/OnlinePropertySale/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/OnlinePropertySale/WEB-INF/lib/org.springframework.web.servlet-3.0.1.RELEASE-A.jar!/META-INF/spring.tld", Long.valueOf(1266566166000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1508810930000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>All Users</title>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write(" <link rel=\"stylesheet\" type=\"text/css\" href=\"jquery/themes/default/easyui.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"jquery/themes/icon.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"jquery/themes/color.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"jquery/demo/demo.css\">\r\n");
      out.write("    <script type=\"text/javascript\" src=\"jquery/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"jquery/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <!-- <script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-1.6.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"http://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script> -->\r\n");
      out.write("    <style>\r\n");
      out.write("    .button{\r\n");
      out.write("border:1px solid #999999; -webkit-border-radius: 42px; -moz-border-radius: 42px;border-radius: 42px;font-size:12px;font-family:times new roman, helvetica, sans-serif; padding: 5px 15px 5px 15px; text-decoration:none; display:inline-block;text-shadow: 1px 1px 0 rgba(255,255,255,0.3);font-weight:bold; color: #000000;\r\n");
      out.write(" background-color: #FFFFFF; background-image: -webkit-gradient(linear, left top, left bottom, from(#FFFFFF), to(#CFCFCF));\r\n");
      out.write(" background-image: -webkit-linear-gradient(top, #FFFFFF, #CFCFCF);\r\n");
      out.write(" background-image: -moz-linear-gradient(top, #FFFFFF, #CFCFCF);\r\n");
      out.write(" background-image: -ms-linear-gradient(top, #FFFFFF, #CFCFCF);\r\n");
      out.write(" background-image: -o-linear-gradient(top, #FFFFFF, #CFCFCF);\r\n");
      out.write(" background-image: linear-gradient(to bottom, #FFFFFF, #CFCFCF);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#FFFFFF, endColorstr=#CFCFCF);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button:hover{\r\n");
      out.write(" border:1px solid #7A7A7A;\r\n");
      out.write(" background-color: #EEEEEE; background-image: -webkit-gradient(linear, left top, left bottom, from(#EEEEEE), to(#C7C7C7));\r\n");
      out.write(" background-image: -webkit-linear-gradient(top, #EEEEEE, #C7C7C7);\r\n");
      out.write(" background-image: -moz-linear-gradient(top, #EEEEEE, #C7C7C7);\r\n");
      out.write(" background-image: -ms-linear-gradient(top, #EEEEEE, #C7C7C7);\r\n");
      out.write(" background-image: -o-linear-gradient(top, #EEEEEE, #C7C7C7);\r\n");
      out.write(" background-image: linear-gradient(to bottom, #EEEEEE, #C7C7C7);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#EEEEEE, endColorstr=#C7C7C7);\r\n");
      out.write("}\r\n");
      out.write(" </style>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function add()\r\n");
      out.write("{\r\n");
      out.write("/* window.location.href=\"addsubadmin.html\"; */\r\n");
      out.write("window.open('adduser.html', 'AddAgent','height=850,width=900,left=200,top=100,overflow: scroll');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}  \r\n");
      out.write("</script> \r\n");
      out.write("<script>\r\n");
      out.write("function update(){\r\n");
      out.write("\t//window.open('updateagent.html', 'AddUser','height=700,width=700,left=200,top=100,overflow: scroll');\r\n");
      out.write("\r\n");
      out.write("     var row = $('#tb').datagrid('getSelected');\r\n");
      out.write("        if (row){\r\n");
      out.write("        \t\r\n");
      out.write("\r\n");
      out.write("         window.open('updateuser.html?username='+row.username,'UpdateAgent','height=850,width=800,left=200,top=100,overflow: scroll');                              \r\n");
      out.write("                    }\r\n");
      out.write("                   else\r\n");
      out.write("                 {\r\n");
      out.write("                $.messager.alert('Warning','Select atleast one row');\r\n");
      out.write("                 } \r\n");
      out.write("     \r\n");
      out.write("               }\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("           <script>\r\n");
      out.write("           \r\n");
      out.write("           function muldel()\r\n");
      out.write("           {\r\n");
      out.write("          /*    alert(\"multiple delete valuessss\");  */\r\n");
      out.write("            \r\n");
      out.write("             var row= $('#tb').datagrid('getSelections');\r\n");
      out.write("\r\n");
      out.write("            /*  alert(row.length); */\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("             if(row.length>0)\r\n");
      out.write("             {\r\n");
      out.write("           \t  var err=[];\r\n");
      out.write("           \t  for(var i=0;i<row.length;i++)\r\n");
      out.write("           \t  {\r\n");
      out.write("           \t      err.push(row[i].username);\r\n");
      out.write("           \t  } \r\n");
      out.write("           \t  \r\n");
      out.write("           \t  \r\n");
      out.write("             \r\n");
      out.write("             $.messager.confirm('My Title', 'Are you sure you want to delete this user?', function(r){\r\n");
      out.write("                 if (r)\r\n");
      out.write("                 {\r\n");
      out.write("             window.location.href=\"agentdeluser.html?username=\"+err\r\n");
      out.write("                 }\r\n");
      out.write("                });\r\n");
      out.write("             }\r\n");
      out.write("             else\r\n");
      out.write("              {\r\n");
      out.write("              $.messager.alert('Warning','Please select atleast one row!');\r\n");
      out.write("              }   \r\n");
      out.write("             \r\n");
      out.write("           } \r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("        function doSearch(value){\r\n");
      out.write("        \t\r\n");
      out.write("        \t$('#tb').datagrid({\r\n");
      out.write("        \t\t\r\n");
      out.write("            \turl:\"agentusergridsearch.html?value=\"+value\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    function reload(){\r\n");
      out.write("    \t$('#tb').datagrid({\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\turl:'agentusersrefresh.html'\r\n");
      out.write("    \t});\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("<script>\r\n");
      out.write("function dateSearch(){\r\n");
      out.write("\t/* alert(\"hi date\"); */\r\n");
      out.write("\tvar fr=$('#fromdate').datebox('getValue');\r\n");
      out.write("\t/* alert(\"hello...\"+fr); */\r\n");
      out.write("\tvar to=$('#todate').datebox('getValue');\r\n");
      out.write("\t\r\n");
      out.write("\tif(new Date(fr)>new Date(to)){\r\n");
      out.write("\t\talert(\"To Date Should not be less than from date\");\r\n");
      out.write("\t}\r\n");
      out.write("\t/* alert(to); */\r\n");
      out.write("\t/* var m = document.getElementById('fromdate').value;\r\n");
      out.write("\tvar from = new Date(m);//converts string to date object\r\n");
      out.write("\talert(from);\r\n");
      out.write("\t\r\n");
      out.write("\tvar f=from.toDateString();\r\n");
      out.write("    alert(f);\r\n");
      out.write("\tvar t=document.getElementById('todate').value;\r\n");
      out.write("\tvar to1=new Date(t);\r\n");
      out.write("\tvar to=to1.toDateString();\r\n");
      out.write("\talert(to); */\r\n");
      out.write("\t/* window.location.href=\"date.html?from=\"+f+\"&to=\"+t;  */\r\n");
      out.write("\telse{\r\n");
      out.write("\t$('#tb').datagrid({\r\n");
      out.write("\t\turl:\"agentusergriddate.html?from=\"+fr+\"&to=\"+to\r\n");
      out.write("\r\n");
      out.write("\t});}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>      \r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("var cd=new Date();\r\n");
      out.write("/* alert(cd); */\r\n");
      out.write("var cdy=cd.getFullYear();\r\n");
      out.write("var cdd=cd.getDate();\r\n");
      out.write("var cdm=cd.getMonth()+1;\r\n");
      out.write("var td=\"\"+cdm+\"/\"+cdd+\"/\"+cdy;\r\n");
      out.write("/* alert(td); */\r\n");
      out.write("$('#fromdate').datebox('setValue',\"01/01/\"+cdy);\r\n");
      out.write("$('#todate').datebox('setValue',td);\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<center>\r\n");
      out.write("   <!--  <table id=\"tb\" class=\"easyui-datagrid\" title=\"All users\" style=\"width:900px;height:300px\" \r\n");
      out.write("    \r\n");
      out.write("    \t   onCheck=\"true\" singleSelect=\"true\" \r\n");
      out.write("    \t\r\n");
      out.write("          rownumbers=\"true\" pagination=\"true\" pageList=\"[10,20,30,40,50,60]\"  showPageList=\"true\" fitColumns=\"false\"  data-options=\"singleSelect:false,url:'usersgrid.html',onDblClickRow:function(index,row){update()},method:'get'\"> -->\r\n");
      out.write("          \r\n");
      out.write("           <table id=\"tb\" class=\"easyui-datagrid\" title=\"UsersList\" style=\"width:1100px;height:250px\" singleSelect=\"false\"  rownumbers=\"true\" pagination=\"true\" fitColumns=\"false\" data-options=\"singleSelect:false,url:'agentsusersgrid.html',onDblClickRow:function(index,row){update()},method:'get'\">\r\n");
      out.write("          \r\n");
      out.write("        <thead> \r\n");
      out.write("        <!-- <div>\r\n");
      out.write("            Search:<input class=\"easyui-searchbox\" data-options=\"prompt:'Username or Firstname',searcher:doSearch\" style=\"width:150px\">\r\n");
      out.write("</div> -->\r\n");
      out.write("<div>\r\n");
      out.write("Search:  <input class=\"easyui-searchbox\" data-options=\"prompt:'Please Input Username',searcher:doSearch\" style=\"width:150px\"/>\r\n");
      out.write("Date Of Joining From:<input id=\"fromdate\" class=\"easyui-datebox\"  style=\"width:100px;\"\r\n");
      out.write("data-options=\"onSelect:dateSearch,editable:true\">\r\n");
      out.write("To:<input id=\"todate\" class=\"easyui-datebox\"  style=\"width:100px;\"\r\n");
      out.write("data-options=\"onSelect:dateSearch,editable:true\">\r\n");
      out.write("<!-- <input type=\"button\" value=\"Search\" style=\"width:60px;\" onclick=\"dateSearch()\"> \r\n");
      out.write(" --><input type=\"button\" value=\"Refresh\" style=\"width:60px;\" onclick=\"reload()\">\r\n");
      out.write("\r\n");
      out.write("<!--  <a href=\"date.html\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" onclick=\"dateSearch()\">Search</a> \r\n");
      out.write(" --> </div>\r\n");
      out.write("&nbsp;\r\n");
      out.write("&nbsp;\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("                 <th align=\"center\" data-options=\"field:'firstname',width:90\">Firstname</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'middlename',width:90,align:'right'\">Middlename</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'lastname',width:90,align:'right'\">Lastname</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'username',width:90\">Username</th>\r\n");
      out.write("                 <!-- <th align=\"center\" data-options=\"field:'password',width:80\">Password</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'conformpassword',width:90\">Conformpassword</th> -->\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'dateofbirth',width:90,align:'right'\">Dateofbirth</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'gender',width:90,align:'right'\">Gender</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'email',width:150\">EmailId</th>\r\n");
      out.write("          \r\n");
      out.write("               <th align=\"center\" data-options=\"field:'mobileno',width:90\">Mobilenumber</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'address',width:90\">Address</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'pincode',width:90,align:'right'\">Pincode</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'country',width:90,align:'right'\">Country</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'state',width:90\">State</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'city',width:90\">City</th>\r\n");
      out.write("                  <th align=\"center\" data-options=\"field:'language',width:90\">Languages Knwon</th>\r\n");
      out.write("                <th align=\"center\" data-options=\"field:'registerdate',width:90,align:'right'\">RegisterDate</th>\r\n");
      out.write("                  \r\n");
      out.write("                \r\n");
      out.write("            </tr>\r\n");
      out.write("            \t\r\n");
      out.write("            \t\r\n");
      out.write("\t      \r\n");
      out.write("\t        </thead> \r\n");
      out.write("    </table></center>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write(" <!-- <div style=\"margin:20px 0;\"></div>\r\n");
      out.write("    <div class=\"easyui-panel\" style=\"width:100%;max-width:400px;padding:30px 60px;\">\r\n");
      out.write("        <input class=\"easyui-searchbox\" data-options=\"prompt:'Please Input Value',searcher:doSearch\" style=\"width:100%\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        function doSearch(value){\r\n");
      out.write("            alert('You input: ' + value);\r\n");
      out.write("            window.location.href=\"search.html?value=\"+value;\r\n");
      out.write("        }\r\n");
      out.write("    </script> -->\r\n");
      out.write("    <div style=\"margin:20px 0;\"  align=\"center\"> \r\n");
      out.write("    \r\n");
      out.write("        <input type=\"button\" name=\"Add\" value=\"Add\" onclick=\"add()\" class=\"button\">&nbsp;&nbsp;&nbsp; \r\n");
      out.write("         <input type=\"button\" name=\"Edit\" value=\"Edit\" onclick=\"update()\" class=\"button\">&nbsp;&nbsp;&nbsp;  \r\n");
      out.write("        <input type=\"button\" name=\"Delete\" value=\"Delete\" onclick=\"muldel()\" class=\"button\">&nbsp;&nbsp;&nbsp; \r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
